### ISSUE TITLE
如何在自己的数据集上使用MDEQ / How to use MDEQ for my own dataset

### ISSUE THREAD

**Issue by qzsrh** [locuslab/mdeq#2]
作者您好!我现在尝试利用MDEQ来训练自己的数据.
数据集:细胞核分割 ,只区分前景和背景.
数据目录结构已与文中所述一致,现在数据已经能够正常载入.
其余还应该在哪些地方作出修改?
非常期待您的回应.

-----------------------------

(Translation by @jerrybai1995):
Hi! I'm trying to use MDEQ to train on my own dataset. The dataset is about cell nucleus segmentation, where we only want to distinguish the foreground from the background. The structure of the data directory has already been organized to be consistent with the repo, and we have verified that the data loading process worked correctly. What else should I do to run the MDEQ model on my dataset? I look forward to your response.

**Comment by shaojieb** [comment]
Hi, thank you for your question! （我接下来用英语回复，方便其他人之后参考）

Overall, there are two ways that I recommend you should adapt other segmentation datasets to this repo:

1. Use MDEQ just like any other segmentation models. Forget about the dataloading/processing/inference code in this repo. If you just go to `lib/models/mdeq.py`, the model should be there already, which takes a `[batch_size x n_channels x H x W]` input and outputs a `[batch_size x n_classes x H x W]` shape tensor. The rest of the training code then should be the same, regardless of which model we use (e.g., PSPNet, PSANet, HRNet, MDEQ, etc.)--- they are just standard processing stuff. Therefore, *if you have existing code, or framework, that can do these (and works on even a simply model)*, I think it might be the easier way to go. But if not, see my option 2 below.

2. If (1) above doesn't work for you, the major thing you should do is to create a file in `lib/datasets` that has the name `[DATASET_NAME].py`, just like the `cityscapes.py` (for the Cityscapes dataset), `lip.py`, etc. Go ahead and take a look at what these files are doing. I would suggest going through `base_dataset.py` and then create a new file based on how `lip.py` was written. You shouldn't need most of the things in `cityscapes.py`, which include some extra tweaks (e.g., they only used 19 out of 33 classes).   After you have your own `[DATASET_NAME].py`, you should create an experiment configuration file just like https://github.com/locuslab/mdeq/blob/master/experiments/cityscapes/seg_mdeq_SMALL.yaml. Change the entries of the configuration file according to how you designed your `[DATASET_NAME].py` (there shouldn't be too many changes, but make sure you do change the `DATASET.DATASET` entry, etc.). You might also want to pretrain the MDEQ model with its unrolled version for a while, by setting the `MODEL.NUM_LAYERS` and `TRAIN.PRETRAIN_STEPS` entries.

After that, you should be able to load and train on the data. The inference should be very similar, and you should only be a bit careful with https://github.com/locuslab/mdeq/blob/master/lib/core/seg_function.py#L148.

Let me know if this helps!

**Comment by qzsrh** [comment]
Thank you very much for your reply, which is very useful to me. I used the second method, which is now working.

**Comment by shaojieb** [comment]
Good to hear! I'm closing this issue then, but feel free to follow up should you have any other questions!
