### ISSUE TITLE
Slightly higher mIoU for cityscapes

### ISSUE THREAD

**Issue by zaccharieramzi** [locuslab/mdeq#4]
Hi,

I have a slightly higher val mIoU than what is reported in the paper when validating the small MDEQ model on the cityscape dataset (76.5 whereas 75.1 is reported in the paper).

I understand that higher is better for mIoU, but I would like to understand if there are sources of variability in the results. 
I didn't change (or at least I don't think so), the parameters for the Broyden method so I think it's not coming from there. I just used the `seg_test.py` module and downloaded your trained small MDEQ, as well as the cityscapes dataset.

**Comment by shaojieb** [comment]
Hi @zaccharieramzi,

Thanks for the question! The variation on Cityscapes is usually pretty small in my experience (e.g., +- 0.4 mIoU stddev). I also noticed this increase in number as well when I uploaded the pretrained model a few weeks ago (but we didn't update the paper), and I'm not sure where the difference come from. I believe I've only run the small model twice, and diverted most of my attention/runs to the large and huge models, so the last time I ran an MDEQ-small was probably 10 or 11 months ago, when the codebase was quite different and it was not possible to reproduce that particular number, I think :) 

It is likely that there are other hyperparameters that are creating the difference; but as I noted above, if you train one from scratch now, you should get somewhere >76.0 (similarly, I trained the huge model quite a few times already and they all yield the same level of performance).

Hope that clarifies things!

**Comment by zaccharieramzi** [comment]
It does, thanks!
