### ISSUE TITLE
Pretrained Pickle files

### ISSUE THREAD

**Issue by seunghyuns98** [locuslab/mdeq#6]
I followed your direction to use pre-trained model, but there occurs some error while loading pretrained model
![image](https://user-images.githubusercontent.com/55797829/112966120-e2b2a080-9184-11eb-8bc0-d5d597e5f4a3.png)

**Comment by shaojieb** [comment]
Hi @seunghyuns98 ,

What version of PyTorch are you using? This seems to be a PyTorch version incompatibility issue (or bug)--- see:
  - https://github.com/UKPLab/sentence-transformers/issues/374#issuecomment-691671699
  - https://github.com/pytorch/pytorch/issues/43766#issuecomment-683548395

I'm running and saving the model with PyTorch 1.6.0, which may be the cause of this. I just tried on my end and can load the model normally. 

But please do let me know if you are unable to solve this by upgrading the PyTorch version.
